name: flutter_window_close
description: Let your Flutter app has a chance to confirm if the user wants to close your app.
version: 0.2.2
homepage: https://github.com/zonble/flutter_window_close

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterWindowClosePlugin
      windows:
        pluginClass: FlutterWindowClosePlugin
      linux:
        pluginClass: FlutterWindowClosePlugin
      web:
        pluginClass: FlutterWindowClosePluginWeb
        fileName: flutter_window_close_web.dart

  